services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs  # Add this line to persist logs on your host      
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000